### ISSUE TITLE
Cannot run it BE locally

### ISSUE THREAD

**Issue by tamir61** [nivg1992/faceplatform#31]
I tried in a few ways...

1.
`docker run -e PF_DATA_FOLDER='/data' -p 5000:5000 -v ./data:/data nivg1992/faceplatform

Unable to find image 'nivg1992/faceplatform:latest' locally
latest: Pulling from nivg1992/faceplatform
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.`

2.
`python3 -m "src.main"

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/Desktop/development/faceplatform/src/main.py", line 11, in <module>
    from src.go2rtc_server_manager import Go2RTCServerManager
  File "/Users/user/Desktop/development/faceplatform/src/go2rtc_server_manager.py", line 6, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'`

3.
`poetry run python -m src.main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 244, in prepare
    _fixup_main_from_name(data['init_main_from_name'])
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 268, in _fixup_main_from_name
    main_content = runpy.run_module(mod_name,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/Desktop/development/faceplatform/src/main.py", line 30, in <module>
    events_manager = EventsManager()
                     ^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/utils/singleton.py", line 6, in get_instance
    instances[cls] = cls(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/events_manager.py", line 11, in __init__
    self.face_recognition = FaceRecognition()
                            ^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/utils/singleton.py", line 6, in get_instance
    instances[cls] = cls(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/face_recognition.py", line 19, in __init__
    self.eventIdMapProccess = multiprocessing.Manager().dict()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/managers.py", line 562, in start
    self._process.start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/Desktop/development/faceplatform/src/main.py", line 30, in <module>
    events_manager = EventsManager()
                     ^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/utils/singleton.py", line 6, in get_instance
    instances[cls] = cls(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/events_manager.py", line 11, in __init__
    self.face_recognition = FaceRecognition()
                            ^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/utils/singleton.py", line 6, in get_instance
    instances[cls] = cls(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/development/faceplatform/src/face_recognition.py", line 19, in __init__
    self.eventIdMapProccess = multiprocessing.Manager().dict()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/managers.py", line 566, in start
    self._address = reader.recv()
                    ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
    raise EOFError
EOFError`

**Comment by nivg1992** [comment]
Thanks @tamirhal 
1. currently the docker doesn't supported arm64 (mac M processor), I will add it soon
2/3. did you run `poetry install` before?

**Comment by tamirhal** [comment]
Got it,
Yes i did
